# Generated by Django 4.0.4 on 2023-02-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_title', models.CharField(max_length=50)),
                ('head', models.CharField(max_length=50)),
                ('author', models.CharField(default='', max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='home/images')),
            ],
        ),
    ]
