# Generated by Django 4.0.4 on 2023-02-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_title', models.CharField(max_length=50)),
                ('author', models.CharField(default='', max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='main/images')),
            ],
        ),
    ]
