# Generated by Django 4.0.4 on 2023-02-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='b_title',
            field=models.CharField(max_length=100),
        ),
    ]
